#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\ManageCustomer\Contract\Rename\RenameCustomer;

include_once __DIR__ . '/../../vendor/autoload.php';

$customerId = 'bef669ae-179e-4329-89b3-5d5820b8ca56';

$processingInteractions = new DemoPublisher(__DIR__ . '/../../.env');

$processingInteractions->sendMessage(
    RenameCustomer::create($customerId, 'Desperado', 'ServiceBus')
);
