#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\Vehicle\Manage\Contracts\Add\AddVehicle;

include_once __DIR__ . '/../../../vendor/autoload.php';

/** @noinspection PhpUnhandledExceptionInspection */
$publisher = new ToolsPublisher(__DIR__ . '/../../../.env');
$publisher->sendMessage(
    AddVehicle::create(
        'bmw',
        'Series 7',
        2018,
        'x777xxxx',
        'black'
    )
);
