#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\DriverDocument\Contracts\Manage\AddDriverDocument;
use App\DriverDocument\Data\DriverDocumentType;

include_once __DIR__ . '/../../../vendor/autoload.php';

/** @noinspection PhpUnhandledExceptionInspection */
$publisher = new ToolsPublisher(__DIR__ . '/../../../.env');
$publisher->sendMessage(
    AddDriverDocument::create(
        (string) DriverDocumentType::passport(),
        \base64_encode(\file_get_contents(__DIR__ . '/docs/passport.jpg')),
        '96b31066-a332-40a4-9142-133eef6be5d6'
    )
);
