#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\Driver\Document\Contracts\Manage\AddDriverDocument;
use App\Driver\Document\Data\DriverDocumentType;

include_once __DIR__ . '/../../../vendor/autoload.php';

$publisher = new ToolsPublisher(__DIR__ . '/../../../.env');
$publisher->sendMessage(
    AddDriverDocument::create(
        (string) DriverDocumentType::passport(),
        \base64_encode(\file_get_contents(__DIR__ . '/docs/passport.jpg')),
        '56216d4b-ca3e-48eb-97e5-a4b72c9261c5'
    )
);
