#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\DriverDocument\Contracts\Manage\AddDriverDocument;
use App\DriverDocument\Data\DriverDocumentType;

include_once __DIR__ . '/../../../vendor/autoload.php';

$publisher = new ToolsPublisher(__DIR__ . '/../../../.env');
$publisher->sendMessage(
    AddDriverDocument::create(
        (string) DriverDocumentType::passport(),
        \base64_encode(\file_get_contents(__DIR__ . '/docs/passport.jpg')),
        '52b1b826-e150-4468-97fb-66cc00cf245e'
    )
);
