#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\Driver\Vehicle\Add\Contract\AddDriverVehicle;

include_once __DIR__ . '/../../../vendor/autoload.php';

$publisher = new ToolsPublisher(__DIR__ . '/../../../.env');
$publisher->sendMessage(
    new AddDriverVehicle(
        '56e91e9b-5283-4f6e-b6a8-da93533217e6',
        'BMW',
        'Series 7',
        2018,
        'x777xxxx',
        'black'
    )
);
