#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\Driver\Vehicle\Add\Contract\AddDriverVehicle;

include_once __DIR__ . '/../../../vendor/autoload.php';

$publisher = new ToolsPublisher(__DIR__ . '/../../../.env');
$publisher->sendMessage(
    new AddDriverVehicle(
        '0da419b4-90fe-4f88-b870-b4008a06ea1a',
        'BMW',
        'Series 7',
        2018,
        'x777xxxx',
        'black'
    )
);
