#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\Driver\Vehicle\Add\Contract\AddDriverVehicle;
use App\Driver\DriverId;

include_once __DIR__ . '/../../../vendor/autoload.php';

$publisher = new ToolsPublisher(__DIR__ . '/../../../.env');
$publisher->sendMessage(
    new AddDriverVehicle(
        processId: '69bd64a8-4492-4b9a-822e-9780f0c6891d',
        driverId: new DriverId('b4591ef4-251f-4fb3-acf1-76352c0e41b5'),
        vehicleBrand: 'BMW',
        vehicleModel: 'Series 7',
        vehicleYear: 2018,
        vehicleRegistrationNumber: 'x777xxxx',
        vehicleColor: 'black'
    )
);
