#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\DriverVehicle\Contract\Manage\AddDriverVehicle;

include_once __DIR__ . '/../../../vendor/autoload.php';

/** @noinspection PhpUnhandledExceptionInspection */
$publisher = new ToolsPublisher(__DIR__ . '/../../../.env');
$publisher->sendMessage(
    AddDriverVehicle::create(
        'ca009fbf-c35a-451b-a65b-fecb45de46f4',
        'bmw',
        'Series 7',
        2018,
        'x777xxxx',
        'black'
    )
);
