#!/usr/bin/env php
<?php

declare(strict_types = 1);

use App\RegisterCustomer\Contract\Register\RegisterCustomer;

include_once __DIR__ . '/../../vendor/autoload.php';

$processingInteractions = new DemoPublisher(__DIR__ . '/../../.env');

$processingInteractions->sendMessage(
    RegisterCustomer::create(
        'Maksim', 'Masiukevich', 'qwerty',
        \sprintf('%s@root.com', \sha1((string) \microtime()))
    )
);
